public_repo_path=imgly/starterkit-apparel-editor-android
public_repo_description=Apparel Editor starter kit that is built on top of the Creative Editor SDK.
gradle_project_name=starter-kit-apparel
app_name=Apparel Editor
package_suffix=apparel
